services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-prompt
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    networks:
      - prompt-network
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6333/readyz"]
      interval: 5s
      timeout: 5s
      retries: 60 # รอได้สูงสุด 5 นาที

  postgres:
    image: postgres:15
    container_name: postgres-prompt
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - prompt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  prompt-network:
    driver: bridge

volumes:
  postgres_data:
  qdrant_data:
